name: Verified commit
description: GitHub Action to create verified commits
inputs:
  path:
    description: |
      Filesystem path of file to be committed
    required: true
  commit-message:
    description: |
      Commit message to be used
    required: true
  ref:
    description: |
      Reference to be updated with commit. This reference must already exist. Defaults to the repository's default branch ref.
    required: false
    default: ''
outputs:
  commit-sha:
    description: SHA of created commit
    value: ${{ steps.commit.outputs.commit-sha }}
runs:
  using: composite
  steps:
    # Get object ids: head commit sha, tree sha
    - shell: bash
      run: ${{ github.action_path }}/inspect-ref.sh "${{ inputs.ref }}"

    # Create blob
    - shell: bash
      run: ${{ github.action_path }}/create-blob.sh "${{ inputs.path }}"

    # Create tree
    - shell: bash
      run: ${{ github.action_path }}/create-tree.sh

    # Create commit
    - shell: bash
      id: commit
      run: ${{ github.action_path }}/create-commit.sh "${{ inputs.commit-message }}"

    # Update ref
    - shell: bash
      run: ${{ github.action_path }}/update-ref.sh "${{ inputs.ref }}"
branding:
  icon: git-commit
  color: purple
