name: Commit
description: GitHub Action to create verified commits
inputs:
  path:
    description: Filesystem path of file to be committed
    required: true
runs:
  using: composite
  steps:
    # Get object ids: head commit sha, tree sha
    - shell: bash
      run: ./get-oids.sh

    # Create blob
    - shell: bash
      run: ./create-blob.sh "${{ inputs.path }}"

    # Create tree
    - shell: bash
      run: ./create-tree.sh
branding:
  icon: git-commit
  color: purple
