name: Verified commit
description: GitHub Action to create verified commits
inputs:
  paths:
    description: |
      Newline-separated list of filesystems path of files to be committed, relative to root of repository.
    required: true
  workspace:
    description: |
      Base directory containing files to be committed, defaults to the GitHub workspace directory path, $GITHUB_WORKSPACE.
    required: false
  commit-message:
    description: |
      Commit message to be used
    required: true
  ref:
    description: |
      Reference to be updated with commit. This reference must already exist. Defaults to the repository's default branch ref.
    required: false
    default: ''
outputs:
  commit-sha:
    description: SHA of created commit
runs:
  using: node12
  main: dist/index.js
branding:
  icon: git-commit
  color: purple
