name: Verified commit
description: Create a verified commit with GitHub Actions
inputs:
  path:
    description: Filesystem path of file to be committed
    required: true
runs:
  using: composite
  steps:
    # Get object ids: head commit sha, tree sha
    - shell: bash
      run: ./get-oids.sh

    # Create blob
    - shell: bash
      run: ./create-blob.sh "${{ inputs.path }}"
