name: Verified commit
description: Create a verified commit with GitHub Actions
inputs:
  path:
    description: Filesystem path of file to be committed
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        gh api graphql \
          --field owner=':owner' \
          --field repo=':repo' \
          --raw-field \
          query='query repoContents($owner: String!, $repo: String!) {
            repository(owner: $owner, name: $repo) {
              defaultBranchRef {
                name
                commit: target {
                  ... on Commit {
                    oid
                    tree {
                      oid
                    }
                  }
                }
              }
            }
          }'
