name: Verified commit
description: Create a verified commit with GitHub Actions
inputs:
  path:
    description: Filesystem path of file to be committed
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      run: |
        response=$( gh api graphql \
          --field owner=':owner' \
          --field repo=':repo' \
          --raw-field \
          query='query repoContents($owner: String!, $repo: String!) {
            repository(owner: $owner, name: $repo) {
              defaultBranchRef {
                name
                commit: target {
                  ... on Commit {
                    oid
                    tree {
                      oid
                    }
                  }
                }
              }
            }
          }' )
        echo HEAD_SHA=$( jq -r '.data.repository.defaultBranchRef.commit.oid' <<< "${response}" ) >> $GITHUB_ENV
        echo TREE_SHA=$( jq -r '.data.repository.defaultBranchRef.commit.tree.oid' <<< "${response}" ) >> $GITHUB_ENV
    - shell: bash
      run: |
        echo head SHA is: $HEAD_SHA.
        echo tree SHA is: $TREE_SHA.
