name: Verified Commit Demo

# npx trigger-repository-dispatch --nwo=swinton/verified-commit --event-type=demo
on:
  workflow_dispatch:
  repository_dispatch:
    types: [demo]

jobs:
  demo:
    name: Demo
    runs-on: ubuntu-latest
    steps:

    - name: Context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: |
        echo "$GITHUB_CONTEXT"

    - name: Checkout
      uses: actions/checkout@v2

    - name: Ensure ref exists
      continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh api /repos/:owner/:repo/git/refs \
          --field sha="$GITHUB_SHA" \
          --field ref="refs/heads/scratch"

    - name: Create file
      run: |
        dd if=/dev/urandom count=1 > myfile

    - name: Commit file
      id: commit
      uses: ./
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: myfile
        commit-message: Committing ./myfile
        ref: refs/heads/scratch

    - name: Inspect environment
      run: |
        echo REF=$REF
        echo HEAD_SHA=$HEAD_SHA
        echo BASE_TREE_SHA=$BASE_TREE_SHA
        echo BLOB_SHA=$BLOB_SHA
        echo TREE_SHA=$TREE_SHA
        echo COMMIT_SHA=$COMMIT_SHA

    - name: Echo commit SHA
      env:
        MY_COMMIT_SHA: ${{ steps.commit.outputs.commit-sha }}
      run: |
        echo "$MY_COMMIT_SHA was created"
        echo "https://github.com/$GITHUB_REPOSITORY/commit/$MY_COMMIT_SHA"
